verbose: 3
jaeger:
  disabled: false
  samplingProbability: 1
  serviceName: Will.IAM
oauth2:
  google:
    clientId: dummy
    clientSecret: dummy
    redirectUrl: dummy
    hostedDomains:
      - domain1
      - domain2
tokens:
  cacheTTL: 10
  enabled: true
listOptions:
  defaultPageSize: 30
